#!/usr/bin/env python3
"""
Alert Node — Mock Email Sender
Subscribes to detection events, generates mock email output,
logs to file in logs/ directory.
When mock_mode is disabled, sends real emails via SMTP.
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import json
import os
import time
from datetime import datetime


class AlertNode(Node):
    def __init__(self):
        super().__init__('alert_node')

        # Parameters
        self.declare_parameter('detection_topic', '/surveillance/detection')
        self.declare_parameter('mock_mode', True)
        self.declare_parameter('recipient', 'rosie.orchestrate@gmail.com')
        self.declare_parameter('subject_prefix', '[SURVEILLANCE ALERT]')
        self.declare_parameter('cooldown_seconds', 30.0)
        self.declare_parameter('project_root', '')

        detection_topic = self.get_parameter('detection_topic').get_parameter_value().string_value
        self.mock_mode = self.get_parameter('mock_mode').get_parameter_value().bool_value
        self.recipient = self.get_parameter('recipient').get_parameter_value().string_value
        self.subject_prefix = self.get_parameter('subject_prefix').get_parameter_value().string_value
        self.cooldown_seconds = self.get_parameter('cooldown_seconds').get_parameter_value().double_value
        self.project_root = self.get_parameter('project_root').get_parameter_value().string_value

        # Ensure logs directory exists
        self.logs_dir = os.path.join(self.project_root, 'logs')
        os.makedirs(self.logs_dir, exist_ok=True)

        self.last_alert_time = 0.0
        self.alert_count = 0
        self.suppressed_count = 0

        self.subscription = self.create_subscription(
            String,
            detection_topic,
            self.detection_callback,
            10
        )

        mode_str = 'MOCK' if self.mock_mode else 'LIVE'
        self.get_logger().info(
            f'Alert Node started [{mode_str}] — recipient: {self.recipient}, '
            f'cooldown: {self.cooldown_seconds}s'
        )

    def detection_callback(self, msg: String):
        try:
            detection = json.loads(msg.data)
        except json.JSONDecodeError as e:
            self.get_logger().error(f'Invalid detection JSON: {e}')
            return

        now = time.time()
        elapsed = now - self.last_alert_time

        # Cooldown check
        if elapsed < self.cooldown_seconds:
            self.suppressed_count += 1
            self.get_logger().debug(
                f'Alert suppressed (cooldown: {self.cooldown_seconds - elapsed:.1f}s remaining). '
                f'Suppressed total: {self.suppressed_count}'
            )
            return

        self.last_alert_time = now
        self.alert_count += 1

        # Build email content
        email = self._build_email(detection)

        if self.mock_mode:
            self._mock_send(email, detection)
        else:
            self._real_send(email, detection)

    def _build_email(self, detection: dict) -> dict:
        timestamp = detection.get('timestamp', 'unknown')
        num_persons = detection.get('num_persons', 0)
        persons = detection.get('persons', [])
        frame_path = detection.get('frame_path', 'N/A')
        frame_filename = detection.get('frame_filename', 'N/A')

        # Human-readable detection details
        person_details = []
        for i, p in enumerate(persons):
            bbox = p.get('bbox', [])
            conf = p.get('confidence', 0)
            person_details.append(
                f'  Person {i+1}: confidence={conf:.2f}, bbox={bbox}'
            )

        subject = (
            f'{self.subject_prefix} {num_persons} person(s) detected — {timestamp}'
        )

        body = f"""SURVEILLANCE ALERT
==================

Timestamp: {timestamp}
Detection ID: {detection.get('detection_id', 'N/A')}
Persons Detected: {num_persons}

Detection Details:
{chr(10).join(person_details)}

Inference Time: {detection.get('inference_ms', 'N/A')}ms
Image Size: {detection.get('image_size', 'N/A')}

Attached Frame: {frame_filename}
Frame Path: {frame_path}

---
This alert was generated by the ROS2 Camera Surveillance System.
"""

        return {
            'to': self.recipient,
            'subject': subject,
            'body': body,
            'attachment': frame_path,
            'attachment_name': frame_filename,
        }

    def _mock_send(self, email: dict, detection: dict):
        """Mock email: print to terminal and log to file."""

        # Terminal output
        separator = '=' * 60
        self.get_logger().info(f'\n{separator}')
        self.get_logger().info(f'📧 MOCK EMAIL #{self.alert_count}')
        self.get_logger().info(f'{separator}')
        self.get_logger().info(f'To: {email["to"]}')
        self.get_logger().info(f'Subject: {email["subject"]}')
        self.get_logger().info(f'Attachment: {email["attachment_name"]}')
        self.get_logger().info(f'{separator}')
        self.get_logger().info(f'{email["body"]}')
        self.get_logger().info(f'{separator}\n')

        # Log to file
        log_date = datetime.now().strftime('%Y-%m-%d')
        log_filename = f'alerts_{log_date}.log'
        log_path = os.path.join(self.logs_dir, log_filename)

        with open(log_path, 'a') as f:
            f.write(f'\n{"=" * 60}\n')
            f.write(f'ALERT #{self.alert_count} — {datetime.now().isoformat()}\n')
            f.write(f'{"=" * 60}\n')
            f.write(f'To: {email["to"]}\n')
            f.write(f'Subject: {email["subject"]}\n')
            f.write(f'Attachment: {email["attachment_name"]}\n')
            f.write(f'{"-" * 40}\n')
            f.write(email['body'])
            f.write(f'\n{"=" * 60}\n')

        # Also save raw JSON event
        events_log = os.path.join(self.logs_dir, f'detection_events_{log_date}.jsonl')
        with open(events_log, 'a') as f:
            event = {
                'alert_id': self.alert_count,
                'time': datetime.now().isoformat(),
                'detection': detection,
                'email': {k: v for k, v in email.items() if k != 'body'}
            }
            f.write(json.dumps(event) + '\n')

        self.get_logger().info(
            f'Alert #{self.alert_count} logged to {log_filename} '
            f'(total alerts: {self.alert_count}, suppressed: {self.suppressed_count})'
        )

    def _real_send(self, email: dict, detection: dict):
        """Real email sending via SMTP — placeholder for future implementation."""
        self.get_logger().warn('Real email sending not yet implemented. Falling back to mock.')
        self._mock_send(email, detection)


def main(args=None):
    rclpy.init(args=args)
    node = AlertNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info(
            f'Shutting down Alert Node. '
            f'Alerts sent: {node.alert_count}, suppressed: {node.suppressed_count}'
        )
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
